name: GLibC Build on Ubuntu.
on:
  push:
    branches:
      - master
      - main

jobs:
  GLibC-Build:
    runs-on: ubuntu-latest

    container:
      image: ubuntu
      options: --user root

    steps:
        - name: ^ Checkout
          uses: actions/checkout@v3

        - name: Create build dir.
          run: mkdir /source

        - name: Copy data.
          run: cp -r * /source/

        - name: Run Init.
          run: cd /source && sh init_ubuntu.sh

        - name: Collect Artifacts.
          run: mkdir -p /artifacts/AppImage && mkdir /artifacts/Binary && cp /runner/page/tlapbot-glibc-x86_64.AppImage /artifacts/AppImage/tlapbot-x86_64.AppImage && cp /runner/page/tlapbot-glibc /artifacts/Binary/tlapbot

        - name: Generate SHA256 checksum for AppImage.
          run: cd /artifacts/AppImage && sha256sum * > sha256sum.txt

        - name: Generate SHA256 checksum for Binary.
          run: cd /artifacts/Binary && sha256sum * > sha256sum.txt

        - name: Upload AppImage.
          uses: actions/upload-artifact@v3
          with:
            name: AppImage
            path: /artifacts/AppImage

        - name: Upload Binary.
          uses: actions/upload-artifact@v3
          with:
            name: Binary
            path: /artifacts/Binary


