on:
  push:
    branches:
      - master
      - main

jobs:
  EXE-Build:
    runs-on: ubuntu-latest

    container:
      image: ubuntu
      options: --user root

    steps:
        - name: ^ Checkout
          uses: actions/checkout@v3

        - name: Create build dir.
          run: mkdir /source

        - name: Copy data.
          run: cp -r * /source/

        - name: Run Init.
          run: cd /source && sh init_windows.sh

        - name: Collect Artifacts.
          run: mkdir -p /artifacts/Binary && cp /runner/page/tlapbot.exe /artifacts/Binary/

        - name: Generate SHA256 checksum for Binary.
          run: cd /artifacts/Binary && sha256sum * > sha256sum.txt

        - name: Upload Binary.
          uses: actions/upload-artifact@v3
          with:
            name: Binary
            path: /artifacts/Binary


